[features]
seeds = false
skip-lint = false
[programs.localnet]
voting = "BQjhXTevM6DdxfRqfn8itMykbuD7gYc4a58v7ahv1Yh1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sushmit_win_ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
